name: screensite
description: Sanctions Screener.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.3.3"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.3.0
  firebase_auth: 4.6.3
  firebase_auth_web: 5.5.3
  firebase_auth_platform_interface: 6.15.3
  cloud_firestore: ^4.0.1
  cloud_functions: ^4.0.1
  equatable: ^2.0.0
  flutter_riverpod: ^2.3.6
  quiver: ^3.1.0
  google_sign_in: ^5.3.3
  jiffy: ^5.0.0
  rxdart: ^0.27.4
  http: ^0.13.4
  url_launcher: ^6.1.7
  country_picker: ^2.0.16
  flutter_json_viewer: ^1.0.1
  flutter_launcher_icons: ^0.9.2
  state_notifier: ^0.7.2+1
  flutter_svg: ^1.1.6
  flutter_dotenv: ^5.0.2
  stack_trace: ^1.11.0
  go_router: ^7.1.1
  common:
    git:
      url: https://github.com/Super-Fast-Forward/flutter_firebase_framework.git
      path: common
  sandbox:
    git:
      url: https://github.com/Super-Fast-Forward/flutter_firebase_framework.git
      path: sandbox
  providers:
    git:
      url: https://github.com/Super-Fast-Forward/flutter_firebase_framework.git
      path: providers
  auth:
    git:
      url: https://github.com/Super-Fast-Forward/flutter_firebase_framework.git
      path: auth
  widgets:
    git:
      url: https://github.com/Super-Fast-Forward/flutter_firebase_framework.git
      path: widgets
  theme:
    git:
      url: https://github.com/Super-Fast-Forward/flutter_firebase_framework.git
      path: theme

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1

  csv: ^5.0.0
  path_provider: ^2.0.2
  permission_handler: ^7.1.0
  universal_html: ^2.0.8
  clipboard:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - assets/Logo_Dark.svg
    - assets/Logo_Light.svg
    - assets/env.development
    - assets/env.production

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
